### ISSUE TITLE
backgrounding the source task in antibody.zsh

### ISSUE THREAD

**Issue by mkwmms** [caarlos0/antibody#17]
I had to delete the & from ```source "$bundle"/*.plugin.zsh &``` in [antibody.zsh](https://github.com/caarlos0/antibody/blob/master/antibody.zsh) so that ZSH wouldn't background the task in order for antibody to work on OS X 10.10.4... zsh and go would print out a lot of verbose output about zsh backgrounding the source task and go performing the routines but none of the plugins actually got sourced.

**Comment by gregf** [comment]
I ran into the same issue on debian linux.

**Comment by mkwmms** [comment]
For what it's worth I had to do delete '&' on RedHat Linux as well. (I don't think it is a systems issue)

**Comment by caarlos0** [comment]
fixed in #19, thanks all!

**Comment by mkwmms** [comment]
No, problem. Awesome package!

**Comment by caarlos0** [comment]
@mkwmms thanks =D
