### ISSUE TITLE
--quiet option

### ISSUE THREAD

**Issue by gregf** [caarlos0/antibody#18]
It would be nice to have some sort of -quiet option. Currently antibody prints out that its cloning the repos every time I start a new shell. I would prefer to see nothing.

**Comment by caarlos0** [comment]
I think this might be a dup of #19, can you check the latest release?

**Comment by gregf** [comment]
I updated earlier this morning thinking the same thing, but our issues are not the same. Every time I open a terminal window I see output like this.

```
/home/gregf/.antibody/zsh-users-zsh-syntax-highlighting
/home/gregf/.antibody/zsh-users-zsh-history-substring-search
/home/gregf/.antibody/berkshelf-berkshelf-zsh-plugin
/home/gregf/.antibody/unixorn-rake-completion.zshplugin
/home/gregf/.antibody/rupa-z
/home/gregf/.antibody/marzocchi-zsh-notify
/home/gregf/.antibody/zsh-users-zsh-completions src
```

**Comment by caarlos0** [comment]
so, this is the `antibody` binary output, and it's meant to be passed to the `antibody.zsh` file, which is sourced and actually loads all the stuff...

How are you using it? Can you paste your `~/.zshrc` here please?

**Comment by gregf** [comment]
Maybe I miss understood something in the readme then. This is all I have in my .zshrc

```
antibody bundle < ~/.zsh/plugins.txt
```

**Comment by caarlos0** [comment]
oh.. you need to source `antibody.zsh`... probably the antibody you're calling is the binary... the binary don't even need to be in your `$PATH`..

```sh
source path/to/antibody.zsh
antibody bundle <  ~/.zsh/plugins.txt
```

This shall fix the issue. I'll add something about this in the README too.

**Comment by gregf** [comment]
Thanks for the clarification. antibody actually can't be in your path I just found out, otherwise the antibody binary is called rather than the function inside antibody.zsh. Maybe the function should be called something else or the binary to avoid this.

**Comment by caarlos0** [comment]
Yes, it might be a good approach..

**Comment by caarlos0** [comment]
So, two actions here:

- [ ] Improve documentation
- [ ] Change antibody binary name (or solve this problem in some other way)

**Comment by caarlos0** [comment]
@gregf I opened a PR fixing that: #23

**Comment by gregf** [comment]
@caarlos0 you rock, thank you! :beers:
