### ISSUE TITLE
Support for module subfolders

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/antibody#21]
Antigen can do stuff like this:

```
antigen bundle zsh-users/zsh-completions src
```

Antibody currently doesn't support that...

**Comment by caarlos0** [comment]
Only reason for that would be zsh-user/zsh-completions, but since [this commit](https://github.com/zsh-users/zsh-completions/commit/5089cd661bd4762d43971da34e7683e91a8b8767), it should be working without it.

Haven't see any other plugins where the main file is in a subfolder... so I'll just skip this one for now.

**Comment by gregf** [comment]
Thanks for this!
