### ISSUE TITLE
Make use of $XDG_CACHE_HOME for .antibody directory

### ISSUE THREAD

**Issue by gregf** [caarlos0/antibody#48]
It would be nice if antibody made use of $XDG_CACHE_HOME for the .antibody dir. If os.GetEnv("XDG_CACHE_HOME") exists you use that dir to store the antibody directory. If it doesn't exist you default to $HOME/.cache/antibody.

**Comment by caarlos0** [comment]
Hi @gregf, thanks for the suggestion.

Seems legit, I'll fix that...

For now, you can `export ANTIBODY_HOME="$XDG_CACHE_HOME/antibody"` if you want to avoid that..

Thanks!
