### ISSUE TITLE
bin is a relative path

### ISSUE THREAD

**Issue by ozkxr** [caarlos0/antibody#56]
...so if you run `antibody bundle asdf/jkl` outside of the home directory it doesn't find it.

**Comment by caarlos0** [comment]
Hi @ozkxr , did you sourced the `antibody.zsh` file?

**Comment by ozkxr** [comment]
Sorry. I think it was my falut. A missconfiguration or something. 
Works fine everywhere.
Close this please.
Sorry, again.

**Comment by caarlos0** [comment]
@ozkxr No problem! Thanks!
