### ISSUE TITLE
Add a command to list installed plugins

### ISSUE THREAD

**Issue by ozkxr** [caarlos0/antibody#60]
People like to know which plugins are installed in their machine.
An `antibody list` could be handy.

PS: I'm really interesed in this project, thats why I'm looking for bugs and potential enhancements. I would love to help but I don't have great skills at golang, I almost know the syntax.

**Comment by caarlos0** [comment]
Hi @ozkxr, yeah, that could be a good addition...

Thanks! :dancer:
