### ISSUE TITLE
compile option/static loading

### ISSUE THREAD

**Issue by mkwmms** [caarlos0/antibody#67]
I can understand if this is beyond the scope of antibody/not the design goal of antibody but...

In an effort to make antibody even faster than it already is, what do you think about having an option to "compile"/statically load your current bundles? 

For example, if you had a `plugins.txt` that looked like:
```
caarlos0/jvm
djui/alias-tips
caarlos0/zsh-mkc
zsh-users/zsh-completions
caarlos0/zsh-open-github-pr
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-history-substring-search
```
and then had `antibody bundle < plugins.txt` in your `~/.zshrc`; this "compile" option would simply create a file with all the full paths to source and would look something like:
```
source /full/path/to/jvm.plugin.zsh
source /full/path/to/jvm.sh
source /full/path/to/alias-tips.plugin.zsh
source /full/path/to/mkc.plugin.zsh
...
```
and then in `antibody.zsh` it would first check for the presence of this file and if it was found it would just do `source name_of_this_file.zsh` instead of doing what it does now (i.e. running the go binary and sourcing the necessary files) 

However, something that would have to be figured out would be if the user has a `~/.zshrc` like:
```
antibody bundle zsh-users/zsh-syntax-highlighting
antibody bundle zsh-users/zsh-history-substring-search
antibody bundle foo
antibody bundle bar
````
instead of the faster way of doing `antibody bundle < plugins.txt` it would be tricky to know when to do `source name_of_this_file.zsh`, because you wouldn't want to do `source name_of_this_file.zsh` for every `bundle <some repo>` in `~/.zshrc`... That is, unless `antibody compile` was a completely separate command from `antibody bundle`.

or am I missing something and this would not actually improve the speed of antibody? (not saying that antibody is slow by any means though...)

I guess my motive is to make my dotfiles completely modular in the sense that I would use antibody to bundle just about everything in my dotfiles. The only downside to doing this is that antibody would, I imagine, inherently be slower than just directly sourcing the files how I normally do in my dotfiles. (As well as it won't add things to `fpath`, if I am not mistaken, but that would be a separate issue...)

**Comment by caarlos0** [comment]
Hi @mkwmms,

Sorry, but I have no plans of adding this to the project mostly because of the issues you cited above...

Thanks!

**Comment by caarlos0** [comment]
I just realized a good way of doing that, it's kind of hacky, but will work just fine ;)

**Comment by caarlos0** [comment]
@mkwmms please check the Hacking session of the readme, that should do the trick.

https://github.com/caarlos0/antibody#hacking

Let me know if it doesn't. Thanks!

**Comment by mkwmms** [comment]
@caarlos0 clever hack! I like it. :smile:

**Comment by caarlos0** [comment]
@mwilliammyers check version `v0.9.1`. A `--static` flag was added to the `bundle` command =)

**Comment by mwilliammyers** [comment]
@caarlos0 will do, thanks!

**Comment by caarlos0** [comment]
@mwilliammyers just now I read your previous comment about fish support.. I guess we can do that, yes.

Maybe some --fish global option or something... will require some changes in design... but, yeah, would work 👍

**Comment by caarlos0** [comment]
let me know if you still interested =)
