### ISSUE TITLE
zsh-theme support

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/antibody#68]
@pragmaticivan reported it to me, let's fix that.

Example: https://github.com/caiogondim/bullet-train-oh-my-zsh-theme

**Comment by edude03** [comment]
Hmm, I'm using the exact theme that's used in the text, but it renders

```
$(build_prompt)
${fg_bold[default]}$(prompt_char) $reset_color
```

Am I missing something?

**Comment by edude03** [comment]
Ah I dug into the ZSH documentation and I found that there is an option called `PROMPT_SUBST` that will evaluate those variables. 

For other people running into this, add
```setopt PROMPT_SUBST```

to you zshrc

**Comment by caarlos0** [comment]
@edude03 thanks for the digging. Can you that docs link to the README? 

Thanks :beers:
